#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

sudo yunohost app checkurl $domain$path -a sickgear
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Set variables
package_dest=/opt/yunohost/sickgear
data_dest=/home/yunohost.app/sickgear
webroot=`echo "$path" | cut -c2-`

# Create user
id -u sickgear &>/dev/null ||  sudo useradd -d /home/yunohost.app/sickgear sickgear

# Make directories
sudo mkdir -p $package_dest
sudo mkdir -p $data_dest

# Install required packages
sudo apt-get install -y libsqlite3-dev libbz2-dev libreadline-dev libssl-dev zlib1g-dev

# Getting last release of SickGear
sudo git clone https://github.com/SickGear/SickGear.git $package_dest/app

# Set rights
sudo chown -R sickgear $package_dest
sudo chown -R sickgear $data_dest
sudo chmod 777 -R $package_dest
sudo chmod 777 -R $data_dest

# Install dependencies
sudo git clone https://github.com/yyuu/pyenv $package_dest/.pyenv

python_ver=2.7.13
sudo PYENV_ROOT=$package_dest/.pyenv $package_dest/.pyenv/bin/pyenv install $python_ver

prevd=`pwd`
cd $package_dest/app
sudo $package_dest/.pyenv/versions/$python_ver/bin/pip install --upgrade pip
sudo $package_dest/.pyenv/versions/$python_ver/bin/pip install --upgrade pyopenssl ndg-httpsclient virtualenv lxml
sudo $package_dest/.pyenv/versions/$python_ver/bin/pip install -r requirements.txt
cd $prevd

# Remove trailing "/" for next commands
path=${path%/}

# Monitor service
sudo yunohost service add sickgear

# Configure Nginx
sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/sickgear.conf

# Default file generation
sudo sed -i "/^ExecStart=/ s|^.*$|ExecStart=$package_dest/.pyenv/versions/$python_ver/bin/python2 $package_dest/app/SickBeard.py --systemd --datadir=$data_dest --port=%I|" $package_dest/app/init-scripts/init.systemd

# Add new sickgear service
sudo cp $package_dest/app/init-scripts/init.systemd /etc/systemd/system/sickgear@.service

# Start/stop SickGear in order to generate config files
sudo service sickgear@8081 start && sudo service sickgear@8081 stop

# Change webroot of SickGear
sudo sed -i "s@web_root = \"\"@web_root = \"/$webroot\"@g" $data_dest/config.ini

# Generate SSOwat conf
sudo service nginx restart
echo $?
sudo yunohost app ssowatconf
sudo service sickgear@8081 start
