#!/bin/bash

domain=$(sudo yunohost app setting sickgear domain)

# Stop SickGear service
sudo service sickgear stop

# Remove all files and directories
sudo rm /etc/nginx/conf.d/$domain.d/sickgear.conf
sudo rm -rf /home/yunohost.app/sickgear
sudo rm -rf /opt/yunohost/sickgear
sudo rm -rf /etc/systemd/system/sickgear@.service
sudo rm -rf /var/run/sickgear

# Disable auto-start at reboot
sudo sudo update-rc.d -f sickgear remove

# Delete SickGear user
sudo userdel sickgear > /dev/null 2>&1

# Restart php & nginx
sudo killall php5-fpm
sudo service php5-fpm start
sudo service nginx reload

# Regenerate SSO configuration
sudo yunohost app ssowatconf

