#!/bin/bash

# Stop SickGear service
sudo service sickgear stop

# Upgrade SickGear from official repository
sudo cd /opt/yunohost/sickgear
sudo git pull

# Restore rights on files
sudo chown -R sickgear /opt/yunohost/sickgear

# Restarting SickGear
sudo service sickgear start

